general {
	hide_cursor =			true
	ignore_empty_input =	true
}

background {
	path =			~/Images/Wallpapers/YnULock.jpg
	blur_passes =	1
	blur_size =		3
}

#Profile picture
image {
	path =			~/Images/Wallpapers/climber-pplock.png

	size =			300
	position =		0, 200
	rounding =		300
}

input-field {
	fade_on_empty =		false
	placeholder_text =

	size =				300, 60
	position =			0, -100
	
	dots_size =			0.35
	dots_spacing =		0.30
	
	inner_color =		rgba(200, 200, 200, 0.4)
	outer_color =		rgba(200, 200, 200, 0.35)
}

#Username
label {
	text =			hkeromne
	position =		0, -35 

	font_family =	Monocraft
	font_size =		30
}

#Time
label {
	text =			$TIME
	
	halign =		right
	valign =		bottom
	position =		-35, 120
	
	font_family =	Monocraft
	font_size =		70
}

#Date
label {
	text =			cmd[update:60] date +"%A, %B %d, %Y"

	halign =		right
	valign =		bottom
	position =		-40, 50

	font_family =	Monocraft
	font_size =		30
}
