#Colors
gray_light="#D8DEE9"
cyan="#05C8C8"

#Style settings
set -g status-position				top
set -g status-left-length			50

set -g status-style					"fg=${gray_light},bg=default"
set -g status-right					""
set -g status-left					""
set -g window-status-current-format	"#[fg=${cyan},bold] #I:#W"
set -g window-status-format			"  #I:#W"

#Session setting
new-session -n				main
set-hook -g session-created	'new-window -n code'
